version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - abcdb

  abcdb:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init_test_data.sql:/docker-entrypoint-initdb.d/init_test_data.sql
